plugins:
  terrytrilla_seo_enabled:
    default: false
    client: false
  terrytrilla_seo_freeze_slugs:
    default: false
    client: false
  terrytrilla_seo_indexable_categories:
    type: category_list
    default: ""
    client: false
  terrytrilla_seo_knowledge_base_categories:
    type: category_list
    default: ""
    client: false
  terrytrilla_seo_hreflang_excluded_locales:
    type: list
    list_type: compact
    default: ""
    client: false
  terrytrilla_seo_og_card_base:
    default: "https://terrytrilla.com/api/og/forum"
    client: false
